In [2]:
import numpy as np

In [7]:
a = np.array(2) #zero dim tensor

In [8]:
a

array(2)

In [9]:
a.ndim

0

In [ ]:
b = np.array([2,3]) #1D tensor and 2D vector
b

array([2, 3])

In [10]:
b.ndim

1

In [15]:
c = np.array([[1,2],[4,5],[7,8]]) #2D tensor and Matrix 
c

array([[1, 2],
       [4, 5],
       [7, 8]])

In [16]:
c.ndim

2

In [19]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #3D tensor
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
d.ndim

3

In [12]:
e = np.zeros((1,5,6))
e

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [13]:
e.ndim

3

#Kurtosis and Skewness