In [1]:
import numpy as np

In [ ]:
np.zeros((2,4), dtype=int)



array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
x3= np.ones((3,4,5), dtype=int)
x3

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [36]:
x3.ndim

3

In [9]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.random.random((3,3))

array([[0.57942015, 0.43090373, 0.88343848],
       [0.0303274 , 0.56973803, 0.32330975],
       [0.35066535, 0.99756855, 0.1401093 ]])

In [40]:
x2 = np.eye(5)
x2
x2.ndim

2

In [38]:
x1= np.empty(3)
x1
x1.ndim

1

In [44]:
x1= np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
x1[:4]

array([0, 1, 2, 3])

In [58]:
x1[::4]

array([0, 4, 8])

In [49]:
x2 = np.random.randint(0,10,(3,4))
x2

array([[9, 9, 2, 4],
       [6, 8, 8, 7],
       [8, 6, 8, 8]], dtype=int32)

In [56]:
x2[:2,:3]

array([[9, 9, 2],
       [6, 8, 8]], dtype=int32)

In [62]:
x2[:, 3::3]

array([[4],
       [7],
       [8]], dtype=int32)

In [63]:
x2[:, 0]

array([9, 6, 8], dtype=int32)

In [64]:
x2[0,:]

array([9, 9, 2, 4], dtype=int32)

In [65]:
x2

array([[9, 9, 2, 4],
       [6, 8, 8, 7],
       [8, 6, 8, 8]], dtype=int32)

In [66]:
sub_array = x2[:2,:2].copy()

In [67]:
sub_array

array([[9, 9],
       [6, 8]], dtype=int32)

In [68]:
x2

array([[9, 9, 2, 4],
       [6, 8, 8, 7],
       [8, 6, 8, 8]], dtype=int32)

In [69]:
sub_array[0,0] = 42

In [70]:
sub_array

array([[42,  9],
       [ 6,  8]], dtype=int32)

In [73]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

In [74]:
cat = np.concatenate([x,y])
cat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
grid = np.array([[1,2,3,4],[5,6,7,8]])
grid

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [77]:
np.concatenate([grid, grid])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
np.concatenate([grid, grid], axis = 1 )

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [79]:
grid

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
x = np.array([11,22,33,44])

In [81]:
np.vstack([x, grid])

array([[11, 22, 33, 44],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [83]:
y = np.array([[99],
              [99]])

In [84]:
np.hstack([grid,y])

array([[ 1,  2,  3,  4, 99],
       [ 5,  6,  7,  8, 99]])

In [85]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [90]:
left , right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [91]:
a = np.array([10, 20, 30, 40, 50, 60])

In [94]:
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

(6,)
6
1
int64


In [100]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
b[:1]

array([[1, 2, 3]])

In [104]:
b[2:]

array([[7, 8, 9]])

In [105]:
b[:, :1]

array([[1],
       [4],
       [7]])

In [106]:
b[:, 2:]

array([[3],
       [6],
       [9]])

In [107]:
b[1,1]

np.int64(5)

In [108]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [109]:
arr[:5]

array([ 5, 10, 15, 20, 25])

In [110]:
arr[5:]

array([30, 35, 40, 45, 50])

In [111]:
arr[2:7]

array([15, 20, 25, 30, 35])

In [112]:
arr[::2]

array([ 5, 15, 25, 35, 45])

In [113]:
arr[::3]

array([ 5, 20, 35, 50])

In [114]:
arr[::-1]

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [115]:
arr[3:7]

array([20, 25, 30, 35])

In [116]:
arr = np.array([
    [10, 20, 30, 40, 50],
    [60, 70, 80, 90, 100],
    [110, 120, 130, 140, 150],
    [160, 170, 180, 190, 200]
])


In [120]:
sub_arr = arr[:2, :3]
sub_arr

array([[10, 20, 30],
       [60, 70, 80]])

In [122]:
sub_arr2= arr[1:3, 2: ]
sub_arr2

array([[ 80,  90, 100],
       [130, 140, 150]])

In [124]:
sub_arr3 = arr[2:]
sub_arr3

array([[110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [127]:
subC = arr[:,:3]
subC

array([[ 10,  20,  30],
       [ 60,  70,  80],
       [110, 120, 130],
       [160, 170, 180]])

In [136]:
stepArray = arr[:, 1::2]
stepArray

array([[ 20,  40],
       [ 70,  90],
       [120, 140],
       [170, 190]])

In [138]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [141]:
arrReshape = arr.reshape(3,4)
arrReshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [144]:
arrRe = arr.reshape(6,2)
arrRe

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [154]:
arr3d = arr.reshape(2,3,2)
arr3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
arr3d.shape

In [161]:
arr = np.arange(1, 13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [177]:
p1,p2,p3= np.vsplit(arr, 3)
print(p1)
print(p2)
print(p3)

[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10 11 12]]


In [179]:
arr = np.arange(1, 25).reshape(4, 6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [180]:
p1,p2 = np.hsplit(arr,2)
print(p1)
print(p2)

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]
[[ 4  5  6]
 [10 11 12]
 [16 17 18]
 [22 23 24]]
